[theme]
# Primary color for interactive elements
primaryColor = "#007bff"

# Background color for the main content area
backgroundColor = "#ffffff"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#f8f9fa"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app
font = "sans serif"

# Base theme - either "light" or "dark"
base = "light"